CREATE TABLE MEMBER(
	ID   VARCHAR2(10) PRIMARY KEY,
	PW   VARCHAR2(10),
	NAME VARCHAR2(20),
	TEL  VARCHAR2(20)
);

CREATE TABLE MBR_HIST(
	REG_DT   DATE PRIMARY_KEY,
	CONTENTS VARCHAR2(100)
);